[project]
name = "dave-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.118.2",
    "openai>=2.3.0",
    "playwright>=1.55.0",
    "pydantic>=2.12.0",
    "weasyprint>=66.0",
]
